# Project information
site_name: dstack
site_url: https://docs.dstack.ai
site_author: Andrey Cheptsov
site_description: >-
  The hassle-free tool for managing ML workflows on any cloud platform.

# Repository
repo_url: https://github.com/dstackai/dstack
repo_name: dstackai/dstack
edit_uri: edit/master/docs/

#Copyright
copyright: Built with <img alt="❤️" class="twemoji" src="https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/svg/2764.svg">️ by <a href="https://github.com/dstackai" target="__blank">dstack</a>

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/dstack_notext.svg
  favicon: images/dstack_fav_32.ico
  icon:
    repo: /custom/github
    edit: material/pencil
  font:
    text: Source Sans Pro
    code: IBM Plex Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: lilac
  #        toggle:
  #          icon: material/weather-night
  #          name: Switch to dark mode
  #      - media: "(prefers-color-scheme: dark)"
  #        scheme: slate
  #        primary: black
  #        accent: light blue
  #        toggle:
  #          icon: material/weather-sunny
  #          name: Switch to light mode
  features:
    #    - navigation.path
    - content.code.copy
    - content.action.edit
    #    - navigation.indexes
    - navigation.tabs
    #    - navigation.instant
    #    - toc.integrate
    - navigation.sections
    #    - navigation.expand
    - navigation.top
    - announce.dismiss
    - navigation.tracking
    - navigation.footer

# Plugins
plugins:
  - blog:
      blog_dir: blog
  - social:
      cards_color:
        fill: "black"
        text: "#FFFFFF"
      cards_font: Roboto
  - search
  - redirects:
      redirect_maps:
        'integrations/experiments/wandb.md': 'tutorials/wandb.md'
        'examples/wandb.md': 'tutorials/wandb.md'
        'examples/tensorboard.md': 'tutorials/tensorboard.md'
        'examples/stable-diffusion.md': 'examples/stable-diffusion.md'
        'examples/github-actions.md': 'tutorials/github-actions.md'
        'installation.md': 'setup/index.md'
  - typeset

# Extensions
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - def_list
  - admonition
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      toc_depth: 2
      permalink: true
  - attr_list
  - md_in_html
  - footnotes

# Customization
extra_css:
  - stylesheets/extra.css
  - stylesheets/termynal.css
extra_javascript:
  - javascripts/extra.js
  - javascripts/termynal.js
extra:
  homepage: /
  generator: false
  analytics:
    provider: google
    property: G-JX21114P7B
  social:
    - icon: /custom/colored/github
      link: https://github.com/dstackai/dstack
    #    - icon: fontawesome/brands/python
    #      link: https://pypi.org/project/dstack/
    - icon: /custom/colored/slack
      link: https://join.slack.com/t/dstackai/shared_invite/zt-xdnsytie-D4qU9BvJP8vkbkHXdi6clQ
    #    - icon: material/rss
    #      link: https://dstack.curated.co/
    - icon: /custom/colored/twitter
      link: https://twitter.com/dstackai
  status:
    new: Recently added
# Page tree
nav:
  - Guides:
      - Get started:
          - Overview: index.md
          - Quick start: quick-start.md
          - Playground: playground.md
          - Setup:
            - CLI: setup/index.md
            - AWS: setup/aws.md
            - GCP: setup/gcp.md
            - Hub: setup/hub.md
      - Usage:
          - Hello world: usage/hello-world.md
          - Python: usage/python.md
          - Artifacts: usage/artifacts.md
          - Deps: usage/deps.md
          - Remote: usage/remote.md
          #        - Environment variables: usage/environment-variables.md
          - Providers: usage/providers.md
          - Cache: usage/cache.md
          - Apps: usage/apps.md
          - Secrets: usage/secrets.md
          - Args: usage/args.md
      - What's next?:
          - Tutorials: tutorials/tensorboard.md
          - Reference: reference/providers/bash.md
      - Support:
          - Troubleshooting: troubleshooting.md
          - Slack: https://join.slack.com/t/dstackai/shared_invite/zt-xdnsytie-D4qU9BvJP8vkbkHXdi6clQ
  #          - Changelog: https://github.com/dstackai/dstack/releases
  #          - Newsletter: https://dstack.curated.co/
  - Tutorials:
      - Experiment tracking:
          - TensorBoard: tutorials/tensorboard.md
          - Weights & Biases: tutorials/wandb.md
      - LLMs:
          - Stable Diffusion: tutorials/stable-diffusion.md
          - Dolly: tutorials/dolly.md
      - CI/CD:
          - GitHub Actions: tutorials/github-actions.md
  - Reference:
      - Reference:
          - CLI:
              - dstack run: reference/cli/run.md
              - dstack ps: reference/cli/ps.md
              - dstack logs: reference/cli/logs.md
              - dstack stop: reference/cli/stop.md
              - dstack rm: reference/cli/rm.md
              - dstack tags: reference/cli/tags.md
              - dstack pull: reference/cli/pull.md
              - dstack push: reference/cli/push.md
              - dstack ls: reference/cli/ls.md
              - dstack cp: reference/cli/cp.md
              - dstack init: reference/cli/init.md
              - dstack config: reference/cli/config.md
              - dstack secrets: reference/cli/secrets.md
              - dstack prune: reference/cli/prune.md
          - Providers:
              - bash: reference/providers/bash.md
              - code: reference/providers/code.md
              - lab: reference/providers/lab.md
              - notebook: reference/providers/notebook.md
              - docker: reference/providers/docker.md
  - Blog:
      - blog/index.md
  - Slack: https://join.slack.com/t/dstackai/shared_invite/zt-xdnsytie-D4qU9BvJP8vkbkHXdi6clQ
  - Twitter: https://twitter.com/dstackai/
#  - Newsletter: https://dstack.curated.co/
#  - GitHub: https://github.com/dstackai/dstack