name: Manual GCP image build for release

on:
  workflow_dispatch:
  push:


jobs:
  gcp-images-build:
    defaults:
      run:
        working-directory: runner
    strategy:
      matrix:
        variants: [ gcp-image, gcp-image-cuda ]
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/531508670106/locations/global/workloadIdentityPools/github-identity-pool/providers/github-id-provider'
          service_account: 'github-actions@dstack.iam.gserviceaccount.com'
          create_credentials_file: true
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Download packer
        run: |
          wget https://releases.hashicorp.com/packer/1.8.0/packer_1.8.0_linux_amd64.zip
          unzip packer_1.8.0_linux_amd64.zip
          chmod +x packer
          cp -R ami/packer/* .
      - name: Run packer
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION//./-}
          ./packer build -var build_id=$VERSION -var build_prefix='' -var dstack_stage=PROD ${{ matrix.variants }}.json
      - name: Publish images
        run: |
          gcloud compute images add-iam-policy-binding dstack-$VERSION --member='allAuthenticatedUsers' --role='roles/compute.imageUser'
          gcloud compute images add-iam-policy-binding dstack-cuda-$VERSION --member='allAuthenticatedUsers' --role='roles/compute.imageUser'
